// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	payload "attendance/model/payload"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAuth is a mock of IAuth interface.
type MockIAuth struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthMockRecorder
}

// MockIAuthMockRecorder is the mock recorder for MockIAuth.
type MockIAuthMockRecorder struct {
	mock *MockIAuth
}

// NewMockIAuth creates a new mock instance.
func NewMockIAuth(ctrl *gomock.Controller) *MockIAuth {
	mock := &MockIAuth{ctrl: ctrl}
	mock.recorder = &MockIAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuth) EXPECT() *MockIAuthMockRecorder {
	return m.recorder
}

// ValidateUserByCredential mocks base method.
func (m *MockIAuth) ValidateUserByCredential(ctx context.Context, data payload.LoginCredential) (*payload.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserByCredential", ctx, data)
	ret0, _ := ret[0].(*payload.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUserByCredential indicates an expected call of ValidateUserByCredential.
func (mr *MockIAuthMockRecorder) ValidateUserByCredential(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserByCredential", reflect.TypeOf((*MockIAuth)(nil).ValidateUserByCredential), ctx, data)
}
