// Package constant ...
package constant

const (
	// DefaultConfigFile ...
	DefaultConfigFile = "config.yaml"
	// StatusPending ...
	StatusPending = "pending"
	// StatusInProgress ...
	StatusInProgress = "in_progress"
	// StatusFailed ...
	StatusFailed = "failed"
	// StatusDone ...
	StatusDone = "done"
)
