// Package constant ...
package constant

const (
	// ContextKey ...
	ContextKey = "context"
	// ContextUserIDKey ...
	ContextUserIDKey = "user_id"
	// ContextEmployeeIDKey ...
	ContextEmployeeIDKey = "employee_id"
	// ContextRoleKey ...
	ContextRoleKey = "role"
	// ContextRequestIDKey ...
	ContextRequestIDKey = "request_id"
	// ContextIPKey ...
	ContextIPKey = "ip_address"
)
